import React from 'react';

import MainBody from '../../shared/components/UIElements/MainBody';
import BlogPost from '../components/BlogPost';
const Blog = props => {
   const BLOGS = [
      {
         id: 'b1',
         image: 'https://source.unsplash.com/1600x900/?beach',
         title: 'https://baconipsum.com/api/?type=all-meat&sentences=5&start-with-lorem=1',
         author: 'Aurora Barnuts',
         content: 'https://baconipsum.com/api/?type=all-meat&sentences=50&start-with-lorem=1',
         datecreated: 'January 14, 2012',
         dateedited: 'January 14, 2012',
         likes: 100,
         comments: 200,
      },
      {
         id: 'b2',
         image: 'https://source.unsplash.com/1600x900/?mountain',
         title: 'https://baconipsum.com/api/?type=all-meat&sentences=5&start-with-lorem=1',
         author: 'Aurora Barnuts',
         content: 'https://baconipsum.com/api/?type=all-meat&sentences=50&start-with-lorem=1',
         datecreated: 'January 14, 2012',
         dateedited: 'January 14, 2012',
         likes: 100,
         comments: 200,
      },
      {
         id: 'b3',
         image: 'https://source.unsplash.com/1600x900/?city',
         title: 'https://baconipsum.com/api/?type=all-meat&sentences=5&start-with-lorem=1',
         author: 'Aurora Barnuts',
         content: 'https://baconipsum.com/api/?type=all-meat&sentences=50&start-with-lorem=1',
         datecreated: 'January 14, 2012',
         dateedited: 'January 14, 2012',
         likes: 100,
         comments: 200,
      },
      {
         id: 'b4',
         image: 'https://source.unsplash.com/1600x900/?space',
         title: 'https://baconipsum.com/api/?type=all-meat&sentences=5&start-with-lorem=1',
         author: 'Aurora Barnuts',
         content: 'https://baconipsum.com/api/?type=all-meat&sentences=50&start-with-lorem=1',
         datecreated: 'January 14, 2012',
         dateedited: 'January 14, 2012',
         likes: 100,
         comments: 200,
      },
      {
         id: 'b5',
         image: 'https://source.unsplash.com/1600x900/?beach',
         title: 'https://baconipsum.com/api/?type=all-meat&sentences=5&start-with-lorem=1',
         author: 'Aurora Barnuts',
         content: 'https://baconipsum.com/api/?type=all-meat&sentences=50&start-with-lorem=1',
         datecreated: 'January 14, 2012',
         dateedited: 'January 14, 2012',
         likes: 100,
         comments: 200,
      },
      {
         id: 'b6',
         image: 'https://source.unsplash.com/1600x900/?mountain',
         title: 'https://baconipsum.com/api/?type=all-meat&sentences=5&start-with-lorem=1',
         author: 'Aurora Barnuts',
         content: 'https://baconipsum.com/api/?type=all-meat&sentences=50&start-with-lorem=1',
         datecreated: 'January 14, 2012',
         dateedited: 'January 14, 2012',
         likes: 100,
         comments: 200,
      },
      {
         id: 'b7',
         image: 'https://source.unsplash.com/1600x900/?city',
         title: 'https://baconipsum.com/api/?type=all-meat&sentences=5&start-with-lorem=1',
         author: 'Aurora Barnuts',
         content: 'https://baconipsum.com/api/?type=all-meat&sentences=50&start-with-lorem=1',
         datecreated: 'January 14, 2012',
         dateedited: 'January 14, 2012',
         likes: 100,
         comments: 200,
      },
      {
         id: 'b8',
         image: 'https://source.unsplash.com/1600x900/?space',
         title: 'https://baconipsum.com/api/?type=all-meat&sentences=5&start-with-lorem=1',
         author: 'Aurora Barnuts',
         content: 'https://baconipsum.com/api/?type=all-meat&sentences=50&start-with-lorem=1',
         datecreated: 'January 14, 2012',
         dateedited: 'January 14, 2012',
         likes: 100,
         comments: 200,
      },

      {
         id: 'b9',
         image: 'https://source.unsplash.com/1600x900/?beach',
         title: 'https://baconipsum.com/api/?type=all-meat&sentences=5&start-with-lorem=1',
         author: 'Aurora Barnuts',
         content: 'https://baconipsum.com/api/?type=all-meat&sentences=50&start-with-lorem=1',
         datecreated: 'January 14, 2012',
         dateedited: 'January 14, 2012',
         likes: 100,
         comments: 200,
      },
      {
         id: 'b10',
         image: 'https://source.unsplash.com/1600x900/?mountain',
         title: 'https://baconipsum.com/api/?type=all-meat&sentences=5&start-with-lorem=1',
         author: 'Aurora Barnuts',
         content: 'https://baconipsum.com/api/?type=all-meat&sentences=50&start-with-lorem=1',
         datecreated: 'January 14, 2012',
         dateedited: 'January 14, 2012',
         likes: 100,
         comments: 200,
      },
      {
         id: 'b11',
         image: 'https://source.unsplash.com/1600x900/?city',
         title: 'https://baconipsum.com/api/?type=all-meat&sentences=5&start-with-lorem=1',
         author: 'Aurora Barnuts',
         content: 'https://baconipsum.com/api/?type=all-meat&sentences=50&start-with-lorem=1',
         datecreated: 'January 14, 2012',
         dateedited: 'January 14, 2012',
         likes: 100,
         comments: 200,
      },
      {
         id: 'b12',
         image: 'https://source.unsplash.com/1600x900/?space',
         title: 'https://baconipsum.com/api/?type=all-meat&sentences=5&start-with-lorem=1',
         author: 'Aurora Barnuts',
         content: 'https://baconipsum.com/api/?type=all-meat&sentences=50&start-with-lorem=1',
         datecreated: 'January 14, 2012',
         dateedited: 'January 14, 2012',
         likes: 100,
         comments: 200,
      },
   ];
   return (
      <MainBody title={props.title}>
         <BlogPost items={BLOGS} />
      </MainBody>
   );
};

export default Blog;
